<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm_repeatedPassword</name>
   <tag></tag>
   <elementGuidId>b049ab6d-9874-40cd-9e48-9ffdac1f8c3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#repeatedPassword</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='repeatedPassword']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ece4857a-88b2-45a6-acd8-478a14d5f018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>b0b7bf6f-3f95-4843-806f-41350f1b72fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repeatedPassword</value>
      <webElementGuid>5371a786-24f6-46b3-9070-7246dc8534a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>634f4995-7a69-40f2-92b8-f1f6b570b4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5f326a57-9f41-43d3-a6a5-c5f4bd542da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeatedPassword&quot;)</value>
      <webElementGuid>d0e769f0-fc1c-4dd2-9246-3c7c96ef8416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='repeatedPassword']</value>
      <webElementGuid>e86fbdfc-8a6c-4735-b4a1-a5fe30632356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customerForm']/table/tbody/tr[12]/td[2]/input</value>
      <webElementGuid>618db8ce-1703-4f9b-adc3-7daea1c0f711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/input</value>
      <webElementGuid>dbf01e9b-b8b6-466c-a2f1-f9af8fd5b024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'repeatedPassword' and @name = 'repeatedPassword' and @type = 'password']</value>
      <webElementGuid>06b5dd8b-88cb-4acd-a145-73fa1c348421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
